<?php

declare(strict_types=1);

/**
 * @internal This class has been auto-generated by the 'norvica/container' library.
 */
final class T implements \Psr\Container\ContainerInterface {
    private const MAP = [];
    private array $resolved = [];

    public function get(string $id)
    {
        if (isset($this->resolved[$id])) {
            return $this->resolved[$id];
        }

        $hash = self::MAP[$id] ?? throw new \Norvica\Container\Exception\NotFoundException("Definition '{$id}' not found.");
        $method = "_{$hash}";

        return $this->resolved[$id] = $this->{$method}();
    }

    public function has(string $id): bool
    {
        return isset(self::MAP[$id]);
    }
};
