<?php

// auto-generated by 'norvica/container'

declare(strict_types=1);

return new class() implements \Psr\Container\ContainerInterface {
    private array $map = [];
    private array $resolved = [];

    public function get(string $id)
    {
        if (isset($this->resolved[$id])) {
            return $id;
        }

        $method = "_{$this->map[$id]}";

        return $this->resolved[$id] = $this->{$method}();
    }

    public function has(string $id): bool
    {
        return isset($this->map[$id]);
    }
};
